### PR TITLE
It was possible to order items with negative quantity

### PR DESCRIPTION
**Pull request by kmasalski**

### CODE REVIEW

**Comment by netferret** [comment]
is it also worth looking at the datatype of uint to prevent negative integers, just a thought.

**Comment by efleming18** [comment]
Hey @kmasalski - how did you do this in the UI? I've been trying and unable to reproduce this.

**Comment by kmasalski** [comment]
Hi,
It is possible when you remove the min attribute of quantity input:

image

**Comment by efleming18** [comment]
Hey @kmasalski - Aha! You are correct and have actually made me think about some other things that should be addressed to go along with this. Here's what I'm thinking:
- We should add model validation to prevent a request at the API level that is outside of a specific range, so something like `Range[0, 150]`
- If that validation fails, display the error in the UI
- If you've altered the Amount, disable the Checkout button until the Update button / process has been invoked
- Prevent the negative quality in the domain model as well (this is what you've done) but I think we can actually use an [OutOfRange GuardClause](https://github.com/ardalis/GuardClauses) here for it 
- Bubble this error up to the frontend.

That error _should really never happen_ if we put that added validation on the API level, but it's still a good idea to do this at the domain model as a last line of defense. I agree that we should throw an exception there as well because if we get to that point somehow, something is _really_ wrong. 

Thoughts?

Would you like to make some of the changes I described above in this PR? I'm happy to work on those in this PR, or merge this one and I can make the additional changes in another PR. I just wanted to give you first crack at them!

**Comment by kmasalski** [comment]
Hi,
Maybe it is a good idea to remove an update button? And refresh the basket after any change?
I totally agree with the rest of the proposed changes. I will implement these changes in this PR.

**Comment by efleming18** [comment]
@kmasalski - cool sounds good! I'll be looking forward to reviewing it!

And let's keep the Update button there for now still - It shows a small piece of the overall application that I think for the time being still holds some value. In the future, if we decide to pull it out though, I'll be sure to tag you on it if you want to work on it!

**Comment by efleming18** [comment]
Hey @kmasalski - this is look good so far! One thing we may have to adjust is what happens when you edit the `min` property on the html via dev tools, then set the quantity to a negative number and click "Update", it correctly shows you the `Quantity must be bigger than 0` error message, and leaves the quantity the value it was beforehand. But at this point, the `Checkout` button is disabled, so I can't checkout until I click "Update" again. 

image

One additional thing is that if there is only one item in the basket and you set the quantity to 0, and click `Checkout` and NOT `Update` first, it allows you to check out an empty order. I think that's what I was hoping to fix by above saying:
- If you've altered the Amount, disable the Checkout button until the Update button / process has been invoked

If we do that, the customer will be forced to "update" the basket and if it ends up clearing the items from the basket, they go back to shopping. 

Or we can scrap the disabling logic, and make it so you click the "Checkout" button that you have to have at least one item in your basket. If not, an error will be displayed. 

Thoughts?

**Comment by efleming18** [comment]
Hey @kmasalski - any update or anything I can help with here?

**Comment by efleming18** [comment]
Hey @kmasalski - have you had a chance to look at the feedback on this PR? I'm happy to take this one over if you'd like. Let me know!

**Comment by kmasalski** [comment]
Hey, @efleming18 you can finish it. I think I will not find the time for it.

**Comment by efleming18** [comment]
Hey @kmasalski - somehow this branch got way out of date and I'm having trouble fixing it/pushing to it anymore. I brought your changes over to another PR with the additional updates we talked about above. Thanks for the contribution here!

**Pull request closed without merging**
