### PR TITLE
Feature add client

### PR DESCRIPTION
**Pull request by michelcedric**
Add Client.Sdk to consume API
- Improve Swagger usage for documentation (it's used in next step)
- Generate client with generate-client.bat in Client.SDK project. Install https://github.com/RicoSuter/NSwag/wiki/NSwagStudio to use it.
- Add IntegrationTest on API use TestServer
- Seed Database on each run of integration test (In memory or SQL server)

### CODE REVIEW

**Comment by michelcedric** [comment]
Hi @efleming18 
Could you check and accept this pull request?
Thanks
Cédric Michel

**Comment by ardalis** [comment]
@michelcedric In the future it would be better if you were to create an issue describing the problem or feature you're proposing adding before creating a pull request. I think NSwagStudio is a nice tool but I don't know that we need to modify this sample to support it or include it out of the box.

**Comment by michelcedric** [comment]
Hi @ardalis 
I understand your remark but there aren't no issue. It's just a personal initiative to add a Integration on the existing API. It's to show how to use TestServer class with a Generated Client with NSwagStudio base on Swagger and also how to seed database for integration test.
Best regards.

**Comment by efleming18** [comment]
Hey @michelcedric - I am going to Close this PR. 

I think what you've done here is a great idea, and I agree with much of what you've done. Since this is a reference application though, we would like to keep it pretty trimmed down and not include something like NSwagStudio out of the box.

We could consider adding a link to a repo (or fork of this repo) in the README that implements what you've done in this PR in case someone is looking for a specific example using NSwagStudio.

**Pull request closed without merging**
