### PR TITLE
Fix empty userName when running WebRazorPages

### PR DESCRIPTION
**Pull request by nudemeth**
Fix issue [#79](https://github.com/dotnet-architecture/eShopOnWeb/issues/79) by adding default username.

### CODE REVIEW

**Comment by rcpacheco** [comment]
Thanks a lot. It works very good!!

**Comment by CESARDELATORRE** [comment]
@ardalis - Please, test this PR and merge. Looks like it should be straightforward based on the PR code I saw.
Thanks for the PR! 👍

**Comment by ardalis** [comment]
Will do

**Comment by ardalis** [comment]
Thanks!

**Comment by nudemeth** [comment]
Thanks! :)

**Pull request merged**
