### PR TITLE
Add functional test project for RazorPages project

### PR DESCRIPTION
**Pull request by rosspace**
I added a functional test project for the razor pages project along with suggestions from #96 to fix an error when trying to make calls to the razor page project from the TestServer.

### CODE REVIEW

**Comment by rosspace** [comment]
I didn't know if it made sense to add the csproj changes to the existing project to support RazorPages. I can continue working on it and merge the two projects if you want.

**Comment by rosspace** [comment]
@ardalis 
It does not like the changes I made to the csproj file. My added test runs correctly but the existing tests give me the following error:

System.IO.FileNotFoundException : Could not load file or assembly 'Microsoft.VisualStudio.Web.CodeGeneration, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified

**Comment by rosspace** [comment]
I don't know if this is because I have version 2.1 installed on my machine but I see references to many 2.1.0.0 dlls in the deps.json and cache files in the bin folder. I upgraded the nuget package for Microsoft.VisualStudio.Web.CodeGeneration.Design in the Web project to 2.1.0.0 and I stopped getting the above error but got a similar one for a different reference. Maybe it just makes sense to wait and add these tests to the 2.1 version.

**Comment by rosspace** [comment]
Looks like you have everything set up already and moved to 2.1 so I'm just closing this out.

**Comment by ardalis** [comment]
Ok, thanks. Yeah, I was just finishing the 2.1 updates and I merged them into master today. I wasn't sure if your changes were still going to be warranted with that or not. It seems like what's in master now works for both Web and WebRazorPages projects.

**Pull request closed without merging**
