### PR TITLE
Migrated to dotnet 8 and Updated packages.

### PR DESCRIPTION
**Pull request by SrushtiPasari94**
Migrated to the new .NET 8. Also updated to new available dotnet 8 packages. 

#963

### CODE REVIEW

**Comment by ardalis** [comment]
We probably don't want this in main until net8 ships and the references are no longer rc versions, right?

**Comment by jamesmontemagno** [comment]
Changed to a new branch that we can merge on Nov. 14th

A few ideas:
1.) Change the version to : 8.0.*-*
or
2.) Add a <AspNetVersion>8.0.0</AspNetVersion>and then  Version="$(AspNetVersion)"  see https://github.com/dotnet/maui/tree/main/src/Workload#nuget-central-package-management

**Comment by jamesmontemagno** [comment]
Beyond that, let's make sure all the docker files are updated such like this PR: https://github.com/dotnet-architecture/eShopOnWeb/commit/fdb1c34d61ff3e9fc56573cba6facb8d7007de78

**Review by jamesmontemagno — APPROVED** [review]

**Comment by SrushtiPasari94** [comment]
> Changed to a new branch that we can merge on Nov. 14th
> 
> A few ideas: 1.) Change the version to : `8.0.*-*` or 2.) Add a `<AspNetVersion>8.0.0-rc.2.23480.2</AspNetVersion>` and then `Version="$(AspNetVersion)"` see https://github.com/dotnet/maui/tree/main/src/Workload#nuget-central-package-management

@jamesmontemagno This changes are added

**Comment by SrushtiPasari94** [comment]
> Beyond that, let's make sure all the docker files are updated such like this PR: [fdb1c34](https://github.com/dotnet-architecture/eShopOnWeb/commit/fdb1c34d61ff3e9fc56573cba6facb8d7007de78)

@jamesmontemagno Updated dockerfile version , launch setting versions to .net8
  Tested changes on docker desktop and azd

**Review by jamesmontemagno — APPROVED** [review]

**Pull request merged**
