### PR TITLE
Feature/manage cancellation token

### PR DESCRIPTION
**Pull request by michelcedric**
Pull request to manage this remarks 

https://github.com/dotnet-architecture/eShopOnWeb/issues/470

I correctly used CancellationToken in repository, WebFile, adapt test, endpoint, and mediatR handlers

### CODE REVIEW

**Review by fingers10 — COMMENTED** [review]
All looks good

**Review by fingers10 — APPROVED** [review]
Good to be merged.

**Comment by michelcedric** [comment]
@ardalis 
If the Pull request is correct, could you check to merged?
Have a good day
Cédric

**Comment by michelcedric** [comment]
Hi @fingers10, @efleming18 @ardalis 
Could you give me a feedback about this PR? Do you think it's possible to merge it?
Best regards

**Comment by fingers10** [comment]
@ardalis  or @efleming18 . Please can you approve the PR?

**Review by ardalis — APPROVED** [review]

**Pull request merged**
