### PR TITLE
Update AsyncRepository to support dictionary

### PR DESCRIPTION
**Pull request by cuno92**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnWeb?pullRequest=445) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnWeb?pullRequest=445) before we can accept your contribution.<br/><br/>:x: cuno92 [sign now](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnWeb?pullRequest=445)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-architecture/eShopOnWeb?pullRequest=445) it.</sub>

**Comment by ardalis** [comment]
Why is this needed?

**Comment by cuno92** [comment]
> Why is this needed?

Dear Ardalis, for faster lookup, especially in loop.

**Comment by roblankey** [comment]
> > Why is this needed?
> 
> Dear @ardalis , for faster lookup, especially in loop.

@cuno92, seems a little confusing to me actually. sure, accessing via a dictionary index is going to be faster than linq, but it also seems like you're trying to solve for a problem we don't know exists. i suppose if it were possible for there to be millions of catalog items, then a dictionary lookup would be quicker, but in that case, i would suggest that `_itemRepository.listAsync(spec)` simply needs a more fine-grained specification no?  

this feels like what you're really trying to do it create an in-memory store of more rows that may be strictly necessary and then trying to filter them effectively, instead of just getting less rows initially.

**Comment by cuno92** [comment]
Hi @roblankey , i got your idea. Thank you for your clarification!

**Pull request closed without merging**
