### PR TITLE
Feature/respect encapsulation

### PR DESCRIPTION
**Pull request by michelcedric**
- Put entity properties as Private
- Add specific method to manipulate entities
- Replace ForSqlServerUseSequenceHiLo (besome obsolete) => UseHilo
- src/Web/Services/CatalogViewModelService.cs => remove useless loop and correctly map property (in CatalogIndexViewModel) in lambda expression. 
- Adapt all unit test with new constructor and method on enity object.
- In the BaseEntity
`
 public virtual int Id { get; protected set; }
`
This property is Virtual to let this one Mockable

### CODE REVIEW

**Comment by efleming18** [comment]
Hey @michelcedric - everything is looking really good. One thing I did notice, is that on the "My Orders" page, the images for the products don't display anymore. I did confirm this is still working in the `master` branch.

Steps to Repro:
- Login
- Add items to your cart
- Checkout
- Navigate to "My Orders" from the hamburger menu
- Click "Details" on your order

image

**Comment by michelcedric** [comment]
@efleming18 : I found the issue. In the master branch it's only working in memory db context because the domain object is modified before send to the view (but that modified the object in memory). 
src/Web/Services/CatalogViewModelService.cs
Of course if you use a real databse this update was not saves: 
I removed this strange behavior. In this case, I also need to modified the CreateOrderAsync to store the url without url root. This one reuses the OrderItem, in memory db context the url was modified but not in database.
src/ApplicationCore/Services/OrderService.cs => CreateOrderAsync use the uri composer to remove the URL root. 
Now it's working well in MemoryContext but also in real database! :) :)

**Comment by efleming18** [comment]
Great! Thanks, @michelcedric !

**Comment by beylkhanovdamir** [comment]
@michelcedric the main goal of such PRs is to stick to DDD principles?

**Comment by michelcedric** [comment]
@beylkhanovdamir Yes, my goal it's to more repect DDD, in this PR, I put all property to private set.
I also move some logical in the domain object.

**Pull request merged**
