### PR TITLE
configured  devcontainer properly

### LINKED ISSUE #382: Devcontainer config is broken
Follow up on #375 

@timheuer  when opening it in VS codespace get below error - 
image

The extension has been renamed to `ms-dotnettools.csharp`.

Also `docker-compose` is not available in  base Oryx image. `dotnet-ef` is also not installed. Typically a development environment should have everything configured and installed.

### PR DESCRIPTION
**Pull request by ankitbko**
Fixed #382 
Added Dockerfile which contains correct setup to run the application. It also includes dotnet-ef tool.
Fixed incorrect extension for c#

### CODE REVIEW

**Comment by efleming18** [comment]
@ankitbko - this has a Merge conflict now, do you want to take a look? I'm sure it's related to the `.vscode/extensions.json` update from the previously merged PR.

**Comment by ankitbko** [comment]
@efleming18 fixed!

**Comment by efleming18** [comment]
I'm working through this now @ankitbko - in both Visual Studio Code and Visual Studio Code in the browser and am getting this error in both. Not sure if it's just an issue with _my_ codespaces, or if you saw this at all as well? 

Exception:
```
System.UnauthorizedAccessException: Access to the path '/home/vscode/.dotnet/3.1.300.toolpath.sentinel' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at Microsoft.Extensions.EnvironmentAbstractions.FileWrapper.CreateEmptyFile(String path)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.<>c__DisplayClass0_0.<CreateIfNotExists>b__0()
   at Microsoft.DotNet.Cli.Utils.FileAccessRetrier.RetryOnIOException(Action action)
   at Microsoft.DotNet.Configurer.FileSystemExtensions.CreateIfNotExists(IFileSystem fileSystem, String filePath)
   at Microsoft.DotNet.Configurer.FileSentinel.Create()
   at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
   at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(IFirstTimeUseNoticeSentinel firstTimeUseNoticeSentinel, IAspNetCertificateSentinel aspNetCertificateSentinel, IFileSentinel toolPathSentinel, Boolean hasSuperUserAccess, DotnetFirstRunConfiguration dotnetFirstRunConfiguration, IEnvironmentProvider environmentProvider)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

I'm going to try this in Visual Studio 2019 as well to see if the same issue happens.

**Comment by ankitbko** [comment]
@efleming18 Good catch. Although it doesnt cause any error for me but the `.dotnet` was being owned by root. I will update the dockerfile to change the ownership.

**Comment by ankitbko** [comment]
Done. Please check once again if you face the issue. For some reason I dont get any error so cant confirm.

image

**Comment by efleming18** [comment]
That seems to have done the trick, @ankitbko ! Thanks for the contribution.

**Pull request merged**
